### ISSUE TITLE
add support for scala 2.12

### ISSUE THREAD

**Issue by fsanaulla** [athieriot/specs2-embedmongo#17]

**Comment by LeonhardtDavid** [comment]
I just created pull request #18 to solve this.

**Comment by athieriot** [comment]
Released as version `0.8.0`. It should appear in the Central Repo in a short while.

Thank you so much for the PR @LeonhardtDavid  !

**Comment by LeonhardtDavid** [comment]
It was a pleasure to help.
Thank you for release it!
